name: Collect DORA Metrics

on:
  repository_dispatch:
    types: [dora-metrics-collect]

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repo
        uses: actions/checkout@v4

      - name: Set up Python (if needed for script)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests PyGithub  # adjust if needed

      - name: Run metric collection script
        run: |
          echo "Collecting DORA metrics for ${{ github.event.client_payload.repo }}"
          python scripts/collect_metrics.py "${{ github.event.client_payload.repo }}"

      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Stage and commit changes
        run: |
          git add metrics/
          git commit -m "Update metrics for ${{ github.event.client_payload.repo }}" || echo "No changes to commit"

      - name: Pull latest from main with rebase
        run: |
          git pull origin main --rebase

      - name: Push changes to main
        run: |
          git push origin main
