name: Collect DORA Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run metrics collector
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: python scripts/collect_metrics.py

      - name: Configure Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Set up authenticated remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Pull latest main branch
        run: git pull origin main --rebase

      - name: Commit updated metrics
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add metrics/
          git commit -m "Update metrics"
          git pull origin main --rebase
          git push origin main

